### ISSUE TITLE
Adicionar campos no model de usuários

### ISSUE THREAD

**Issue by Zambom** [Projetao-2019-2/project-toth#10]
Adicionar campos para armazenar:

- Link das redes sociais do usuário (Facebook, Instagram, Twitter)
- Imagem do usuário

Obs: atualizar a documentação com os novos campos

**Comment by heitorado** [comment]
Solved at PR #14

**Comment by heitorado** [comment]
Algum recurso onde eu possa ter uma base de como anexar imagens a um model?

**Comment by heitorado** [comment]
Primeiro requisito desenvolvido em #15

**Comment by Zambom** [comment]
> Algum recurso onde eu possa ter uma base de como anexar imagens a um model?

Em posts tem upload de imagens... Ele usa o pacote multer, cuja configuração está em "config/multer.js". Basicamente é criar uma nova variável para armazenar as confs relacionado ao model de usuário (que serão quase identicas às de posts, só tirar o que tiver relacionado a outros tipos de arquivos).

**Comment by heitorado** [comment]
Adicionando tais configs no multer, ainda é preciso fazer algo no model/controller/routes?

**Comment by Zambom** [comment]
> Adicionando tais configs no multer, ainda é preciso fazer algo no model/controller/routes?

no router tem que "falar" pro multer tratar aquela rota e no controller tem que tratar para colocar o caminho da imagem no campo.

**Comment by heitorado** [comment]
aye aye, captain.

**Comment by heitorado** [comment]
> no router tem que "falar" pro multer tratar aquela rota e no controller tem que tratar para colocar o caminho da imagem no campo.

Os dois últimos commits enviados tentam implementar essa funcionalidade. No entanto não consegui fazer a rota de update. Fiz a rota de create me baseando no controller de Post, mas quando vi o método que faz o Update, achei confuso e não consegui progredir. Gostaria de ajuda.

**Comment by Zambom** [comment]
> > no router tem que "falar" pro multer tratar aquela rota e no controller tem que tratar para colocar o caminho da imagem no campo.
> 
> Os dois últimos commits enviados tentam implementar essa funcionalidade. No entanto não consegui fazer a rota de update. Fiz a rota de create me baseando no controller de Post, mas quando vi o método que faz o Update, achei confuso e não consegui progredir. Gostaria de ajuda.

O lance do update de posts é que tem que tratar vários arquivos e tals. Em usuários é bem mais simples, basta verificar se foi feito algum upload de imagem e, em caso positivo, colocar o novo path no campo, do contrário não faz nada.

**Comment by heitorado** [comment]
Done. (I guess)
